name: CI

on:
  workflow_dispatch:
  push:
    paths:
      - 'packages/**/src/**.ts'
      - 'packages/**/src/**.mts'
      - 'packages/**/src/**.mjs'
      - 'packages/**/src/**.js'
      - 'packages/**/src/**.json'
      - '.github/workflows/**.yml'

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v4.1.0
        with:
          node-version: 22
      - name: Dependencies
        uses: pnpm/action-setup@v4.0.0
        with:
          run_install: true
      - name: Lint
        run: pnpm -r lint
      - name: Build
        run: pnpm -r prepublishOnly
